import argparse
from dataclasses import asdict
from datetime import date, datetime, timedelta, timezone
import hashlib
import json
from pathlib import Path
from .data import fetch, parse, daily, atomic_write, SOURCE
from .forecast import forecast_daily
from .model import Config
from .validation import hindcast, summarize, tune
from . import __version__


def dump(path,obj):atomic_write(path,json.dumps(obj,indent=2,allow_nan=False).encode())

def main():
    p=argparse.ArgumentParser(description='Penticton-only F10.7 research forecast')
    p.add_argument('command',choices=['fetch','forecast','validate'])
    p.add_argument('--data',default='data');p.add_argument('--output',default='results')
    p.add_argument('--as-of',help='UTC date: use only observations through this date')
    p.add_argument('--config',help='Frozen JSON config generated by validation')
    p.add_argument('--tune',action='store_true')
    args=p.parse_args(); folder=Path(args.data); out=Path(args.output)
    if args.command=='fetch':
        obs,meta=fetch(folder); print(json.dumps(meta,indent=2));return
    raw=(folder/'fluxtable.txt').read_bytes();obs,rejected=parse(raw.decode('utf-8-sig'))
    series=daily(obs)
    if args.as_of:series=[r for r in series if r[0]<=date.fromisoformat(args.as_of)]
    config=Config(**json.loads(Path(args.config).read_text())) if args.config else Config()
    provenance={'source':SOURCE,'snapshot_sha256':hashlib.sha256(raw).hexdigest(),
                'calculated_at_utc':datetime.now(timezone.utc).isoformat(),'software_version':__version__,
                'rejected_rows':rejected,'archive_vintage_hindcast':True,
                'limitation':'Historical publication times and revisions are unavailable; this is not a vintage-correct operational replay.'}
    if args.command=='forecast':
        result=forecast_daily(series,config);result['provenance']=provenance
        dump(out/'forecast.json',result);print(json.dumps(result,indent=2));return
    audit=[]
    if args.tune:config,audit=tune([r for r in series if r[0].year<=2016],config)
    training=[r for r in series if r[0].year<=2012]
    late={}
    for o in obs:
        if o.time.hour>20:late[o.time.date()]=(o.time,o.observed)
    rows=hindcast(series,config,late=late)
    test=[r for r in rows if r['origin']>='2017-01-01']
    if not test:raise ValueError('No final-test cases (2017 onward)')
    report=summarize(test,training)
    report.update({'provenance':provenance,'parameters':asdict(config),'tuning':audit,
                   'split':{'initialization':'2004-2012','tuning':'2013-2016','test':'2017 onward'},
                   'alerts':'not implemented: no verified historical threshold',
                   'intraday_experiment':'drift only; paired noon-vs-late comparison required'})
    last_date=series[-1][0];end=last_date.replace(day=1);start=(end-timedelta(days=1)).replace(day=1)
    month=[r for r in test if str(start)<=r['origin']<str(end)]
    report['last_complete_month']={'start':str(start),'end_exclusive':str(end),**summarize(month,training)}
    # Pair late experiment with noon baseline on the same targets.
    late_keys={(r['origin'],r['target']) for r in test if r['method']=='adaptive_drift_late'}
    paired=[r for r in test if r['method'] in ('adaptive_drift','adaptive_drift_late') and (r['origin'],r['target']) in late_keys]
    report['late_paired']=summarize(paired,training)
    dump(out/'validation.json',report);dump(out/'config.json',asdict(config))
    atomic_write(out/'hindcasts.jsonl',('\n'.join(json.dumps(r,allow_nan=False) for r in rows)+'\n').encode())
    print(json.dumps({'test_forecasts':len(test),'methods':report['methods'],'output':str(out)},indent=2))

if __name__=='__main__':main()
